### ISSUE TITLE
Recipe-app-project: set up the Kanban board

### ISSUE THREAD

**Issue by Kel-nana** [Kel-nana/Recipe-app#12]
### Features
- The GitHub project's Kanban board is created from scratch.
 - Tasks are created based on project requirements with titles and complexity points.
 - Assignee's are designated fairly for each task.
 - All cards now have assignee's with balanced workloads.
 - 
 ### Group Members:

- [`Kelvin`](https://github.com/Kel-nana) 
- [ `Enobong`](https://github.com/Enoisong)

###  Link to Kanban board setup
[`click here`](https://github.com/users/Kel-nana/projects/4/views/1)

**Comment by divinecharlotte** [comment]
Hi @Team    , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- Clean code👍 
- Implemented some project requirements   👍 

 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [ ] kindly consider adding the `In Review` column to meet the project requirement
- [ ] Kindly consider distributing tasks in a fair way based on the points on tasks assigned to [Kelvin](https://github.com/Kel-nana) it really shows a big difference in sharing tasks which is not fair and not meeting the project requirements

_Check the comments under the review._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kel-nana** [comment]
### Implemented reviewers changes

- Addition of in review column
- Re-distribution of task points

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info ✔️
- Tasks distributed equally ✔️  

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
